name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9  # Ensure this matches the version in package.json
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: pnpm store prune  # Optional: Clears the pnpm cache
      - run: pnpm install
      - run: pnpm build
