name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Checkout your code
      - uses: actions/setup-node@v4  # Setup Node.js version
        with:
          node-version: '18'
      - run: npm install -g pnpm  # Install pnpm globally
      - run: pnpm --version  # Verify pnpm version

      - run: pnpm install  # Install dependencies
      - run: pnpm build  # Build the project
